window.dlaMasterData = [
    // ==========================================
    // PART 1: OVERVIEW & HEALTH CONDITIONS (Q1 - Q33)
    // ==========================================
    { step: 'part1', qNum: 'Question 1', officialTitle: 'Child Full Name', component: 'Eligibility Baseline', pitfall: 'Using an informal nickname rather than the child\'s full legal name.', guidance: 'Must match official birth certificate and Child Benefit records.', buzzwords: 'Legal identity verification.', exampleASD: '[Child] official registered name matches birth certificate and clinical NHS records exactly.' },
    { step: 'part1', qNum: 'Question 2', officialTitle: 'Child Date of Birth', component: 'Eligibility Baseline', pitfall: 'Misjudging statutory age qualifying rules.', guidance: 'Establishes age criteria for care (birth+) and mobility (higher at 3+, lower at 5+).', buzzwords: 'Statutory child age criteria.', exampleASD: 'Born [DOB], qualifying under standard statutory child disability allowance criteria.' },
    { step: 'part1', qNum: 'Question 3', officialTitle: 'Child Residential Address', component: 'Residency Baseline', pitfall: 'Failing to state primary permanent residence.', guidance: 'Confirm where the child permanently lives and receives care.', buzzwords: 'Permanent UK habitual residence.', exampleASD: 'Resides permanently at home with primary family caregiver providing daily ASD care.' },
    { step: 'part1', qNum: 'Question 4', officialTitle: 'Who is Filling in this Form?', component: 'Guardian Details', pitfall: 'Not specifying full parental responsibility.', guidance: 'Confirm legal parental responsibility and day-to-day caring role.', buzzwords: 'Primary legal parent and 24-hour caregiver.', exampleASD: 'Completed by primary parent providing round-the-clock specialized care for child with ASD.' },
    { step: 'part1', qNum: 'Question 5', officialTitle: 'Does the Child Live with You?', component: 'Residency Test', pitfall: 'Omitting custody splits or residential care stays.', guidance: 'Confirm full-time 365-day care at home.', buzzwords: 'Full-time parental care.', exampleASD: 'Lives with claimant full-time under continuous daily parental ASD care and management.' },
    { step: 'part1', qNum: 'Question 6', officialTitle: 'Nationality and Immigration Status', component: 'Residency Test', pitfall: 'Leaving UK residency gaps unexplained.', guidance: 'Confirms UK habitual residence test compliance.', buzzwords: 'Habitual UK resident.', exampleASD: 'UK citizen habitually resident in the UK meeting all statutory residency rules.' },
    { step: 'part1', qNum: 'Question 7', officialTitle: 'Does the Child Attend School or Nursery?', component: 'Educational Baseline', pitfall: 'Stating standard full-time attendance if they have reduced hours or masking burnout.', guidance: 'Detail school setting, reduced timetables, or Emotionally-Based School Avoidance.', buzzwords: 'SEND Support Register, Reduced timetable, Masking burnout.', exampleASD: 'Attends mainstream school with extensive ASD accommodations, sensory room breaks, and high masking burnout.' },
    { step: 'part1', qNum: 'Question 8', officialTitle: 'Name and Address of School', component: 'Educational Evidence', pitfall: 'Giving generic office details.', guidance: 'Provide campus address and direct SEND department contacts.', buzzwords: 'Designated educational placement.', exampleASD: 'Enrolled at [School Name], under direct daily support from the school SEND team.' },
    { step: 'part1', qNum: 'Question 9', officialTitle: 'Who Knows the Child Best at School?', component: 'Educational Contact', pitfall: 'Listing the headteacher instead of classroom staff.', guidance: 'Name the specific SENCO or 1-to-1 Teaching Assistant who manages meltdowns.', buzzwords: 'Special Educational Needs Coordinator (SENCO), 1-to-1 Support Assistant.', exampleASD: '[SENCO Name] and dedicated 1-to-1 Teaching Assistant who manage daily ASD dysregulation and transitions.' },
    { step: 'part1', qNum: 'Question 10', officialTitle: 'Does the Child Receive Extra Educational Help?', component: 'SEN Provision', pitfall: 'Downplaying informal accommodations.', guidance: 'Detail workstation modifications, ear defenders in class, and visual schedules.', buzzwords: 'Visual timetable, Quiet sensory workstation, 1-to-1 adult scaffolding.', exampleASD: 'Requires 1-to-1 visual schedule prompts, ear defenders in class, and access to a low-arousal sensory area.' },
    { step: 'part1', qNum: 'Question 11', officialTitle: 'Does the Child Have an EHCP or IEP?', component: 'Statutory SEN', pitfall: 'Ticking No while an EHCP assessment is underway.', guidance: 'State active EHCP status or active statutory assessment in progress.', buzzwords: 'Statutory EHCP active, Section F quantified provision.', exampleASD: 'Maintains an active EHCP detailing significant autistic social, communication, and sensory processing provisions.' },
    { step: 'part1', qNum: 'Question 12', officialTitle: 'Does the Child Stay at Boarding School?', component: 'Institutional Rule', pitfall: 'Failing to confirm standard home return.', guidance: 'Confirm child lives at home full-time.', buzzwords: 'Day-pupil returning home daily.', exampleASD: 'Day-pupil only; returns home daily requiring multi-hour parental decompression after masking at school.' },
    { step: 'part1', qNum: 'Question 13', officialTitle: 'Does the Child Attend Clubs or Daycare?', component: 'Social Functioning', pitfall: 'Writing No without explaining the sensory reason.', guidance: 'Explain that noisy group environments cause severe sensory meltdowns.', buzzwords: 'Excluded from mainstream extracurriculars due to sensory overload.', exampleASD: 'Cannot access standard clubs; overwhelming acoustics and unstructured socialization trigger acute autistic panic.' },
    { step: 'part1', qNum: 'Question 14', officialTitle: 'Does Anyone Else Help Look After the Child?', component: 'Care Network', pitfall: 'Downplaying the intense specialized nature of the care.', guidance: 'Clarify that relatives cannot manage the child\'s autistic meltdowns or safety risks.', buzzwords: 'Specialist ASD care requirement, Cannot be left with untrained carers.', exampleASD: 'Care is strictly parental; relatives cannot safely interpret non-verbal cues or de-escalate violent sensory meltdowns.' },
    { step: 'part1', qNum: 'Question 15', officialTitle: 'Does the Child Receive Help from Social Services?', component: 'Social Care', pitfall: 'Thinking lack of social services invalidates medical needs.', guidance: 'State Early Help, Disabled Children\'s Team, or confirm all care is parental.', buzzwords: 'Early Help Plan / Specialist parental care.', exampleASD: 'Supported via Early Help / all intensive neurodevelopmental support is provided entirely by parents at home.' },
    { step: 'part1', qNum: 'Question 16', officialTitle: 'Is the Child in Local Authority Care?', component: 'Care Order', pitfall: 'Misinterpreting parental legal responsibility.', guidance: 'Confirm full private parental custody.', buzzwords: 'Full parental responsibility retained.', exampleASD: 'Resides permanently with parents under full private parental responsibility.' },
    { step: 'part1', qNum: 'Question 17', officialTitle: 'Is the Child Currently in Hospital or Residential Care?', component: 'Institutional Test', pitfall: 'Leaving blank.', guidance: 'Confirm the child is currently cared for at home.', buzzwords: 'Home-based care.', exampleASD: 'Not in hospital; residing permanently at home under continuous family care.' },
    { step: 'part1', qNum: 'Question 18', officialTitle: 'Hospital Admission Dates (If Applicable)', component: 'Institutional Test', pitfall: 'N/A confusion.', guidance: 'Mark as Not Applicable.', buzzwords: 'Not applicable.', exampleASD: 'Not applicable - cared for at home.' },
    { step: 'part1', qNum: 'Question 19', officialTitle: 'Who Pays for Hospital / Care Costs?', component: 'Funding Rule', pitfall: 'N/A confusion.', guidance: 'Mark Not Applicable.', buzzwords: 'Not applicable.', exampleASD: 'Not applicable.' },
    { step: 'part1', qNum: 'Question 20', officialTitle: 'Immigration Control Restrictions', component: 'Residency Rule', pitfall: 'Incorrect declaration.', guidance: 'Confirm UK citizen exemption.', buzzwords: 'Exempt from immigration control.', exampleASD: 'Full UK citizen exempt from immigration control.' },
    { step: 'part1', qNum: 'Question 21', officialTitle: 'Other Benefits Received for the Child', component: 'Benefit Baseline', pitfall: 'Omitting standard benefits.', guidance: 'List standard Child Benefit.', buzzwords: 'Standard statutory child benefits.', exampleASD: 'Receives standard UK Child Benefit.' },
    { step: 'part1', qNum: 'Question 22', officialTitle: 'Previous DLA Claim History', component: 'Claim History', pitfall: 'Omitting past claim details.', guidance: 'Confirm initial claim or review status.', buzzwords: 'Initial child DLA submission.', exampleASD: 'Initial application following escalation of autistic difficulties and high-care daily needs.' },
    { step: 'part1', qNum: 'Question 23', officialTitle: 'What Illnesses, Disabilities or Conditions Does the Child Have?', component: 'Eligibility Baseline', pitfall: 'Waiting for a formal diagnostic report before applying.', guidance: 'Formal diagnosis is not required. State autism under clinical investigation.', buzzwords: 'Autism Spectrum Disorder (ASD), Sensory Processing Disorder (SPD), Pathological Demand Avoidance (PDA).', exampleASD: '[Child] is under assessment for Autism Spectrum Disorder (ASD) and Sensory Processing Disorder (SPD), with severe sensory meltdowns and receptive communication deficits.' },
    { step: 'part1', qNum: 'Question 24', officialTitle: 'What Medications Does the Child Take?', component: 'Medical Management', pitfall: 'Leaving blank if unmedicated.', guidance: 'List prescribed melatonin, laxatives, and daily sensory diet routines.', buzzwords: 'Prescribed melatonin for circadian failure, Sensory compression therapies.', exampleASD: 'Prescribed daily melatonin for circadian sleep phase failure; managed via non-pharmacological sensory diets.' },
    { step: 'part1', qNum: 'Question 25', officialTitle: 'Treatments, Therapies and Interventions', component: 'Clinical Input', pitfall: 'Omitting home-based therapies.', guidance: 'Detail Occupational Therapy (OT), joint compressions, and sensory decompression spaces.', buzzwords: 'Proprioceptive sensory diet, Occupational therapy sensory integration, Speech therapy.', exampleASD: 'Follows an Occupational Therapy sensory diet involving proprioceptive joint compressions, weighted aids, and visual schedules.' },
    { step: 'part1', qNum: 'Question 26', officialTitle: 'GP Name and Surgery Details', component: 'Medical Contact', pitfall: 'Incomplete surgery contact details.', guidance: 'Provide full practice name, address, and phone number.', buzzwords: 'Registered General Practitioner overseeing referrals.', exampleASD: 'Dr [Name], [Surgery Address], holding complete medical history and pediatric neurodevelopmental referrals.' },
    { step: 'part1', qNum: 'Question 27', officialTitle: 'Hospital Consultant or Paediatrician Details', component: 'Specialist Evidence', pitfall: 'Listing the hospital without naming the consultant.', guidance: 'Name the specific Community Paediatrician conducting the assessment.', buzzwords: 'Consultant Community Paediatrician, Child Development Centre.', exampleASD: 'Dr [Name], Consultant Community Paediatrician at [Clinic], leading formal multidisciplinary ASD diagnostic evaluation.' },
    { step: 'part1', qNum: 'Question 28', officialTitle: 'Educational Psychologist or SENCO Contact', component: 'Educational Evidence', pitfall: 'Leaving blank if reports are pending.', guidance: 'Provide contact details for the school SENCO or Educational Psychologist.', buzzwords: 'Educational Psychology Service, School SENCO.', exampleASD: '[SENCO Name], coordinating specialized ASD classroom adaptations, sensory timeouts, and visual aids.' },
    { step: 'part1', qNum: 'Question 29', officialTitle: 'Other Therapists Involved in Care', component: 'Therapy Network', pitfall: 'Omitting Speech Therapists or Private OTs.', guidance: 'List every private or NHS Occupational Therapist, SALT, or CAMHS worker.', buzzwords: 'Occupational Therapist, Speech & Language Therapist, CAMHS.', exampleASD: 'Specialist Pediatric Occupational Therapist providing sensory integration plans and Speech Therapist supporting social communication.' },
    { step: 'part1', qNum: 'Question 30', officialTitle: 'Recent Medical Tests, Assessments or Reports', component: 'Clinical Reports', pitfall: 'Failing to mention clinical paperwork attached.', guidance: 'List developmental assessments, ADOS-2 reports, and sensory profile scores.', buzzwords: 'ADOS-2 Assessment, Sensory Profile 2 Report, Pediatric Neurodevelopmental Summary.', exampleASD: 'ADOS-2 clinical evaluation summary and Occupational Therapy Sensory Profile attached demonstrating severe processing differences.' },
    { step: 'part1', qNum: 'Question 31', officialTitle: 'Upcoming Appointments or Admissions', component: 'Active Pathway', pitfall: 'Leaving blank while waiting for clinic dates.', guidance: 'Confirm child is on active NHS pediatric clinic waiting lists.', buzzwords: 'Active NHS multi-disciplinary autism diagnostic pathway.', exampleASD: 'Awaiting scheduled Multi-Disciplinary Autism Assessment clinic review and follow-up pediatric development clinics.' },
    { step: 'part1', qNum: 'Question 32', officialTitle: 'Special Aids, Equipment or Adaptations', component: 'Equipment Needs', pitfall: 'Writing None because the child does not use a wheelchair.', guidance: 'Detail ear defenders, chewelry, weighted blankets, visual timers, and bed rails.', buzzwords: 'Sensory regulation aids, Active noise-canceling defenders, Proprioceptive weighted items.', exampleASD: 'Requires active noise-canceling ear defenders, silicone chewelry, a 3kg weighted blanket, visual timers, and high-bolt locks.' },
    { step: 'part1', qNum: 'Question 33', officialTitle: 'Other Health Professionals Involved', component: 'Care Network', pitfall: 'Leaving blank.', guidance: 'List specialist health visitors or pediatric community nurses.', buzzwords: 'Specialist Community Health Visitor.', exampleASD: 'Supported by Specialist Health Visitor for developmental delays, sensory food aversions, and sleep failure.' },

    // ==========================================
    // PART 2: OUTDOOR MOBILITY (Q34 - Q53)
    // ==========================================
    { step: 'mobility', qNum: 'Question 34', officialTitle: 'Can the Child Walk Outdoors on Familiar Routes Without Help?', component: 'Higher Rate Mobility (Walking Test)', pitfall: 'Assuming walking questions only count if paralyzed.', guidance: 'Explain that sensory overload, hypotonia, and autistic shutdowns halt walking.', buzzwords: 'Severe sensory distress upon walking, Extreme behavioral refusal, Autistic shutdown.', exampleASD: 'While [Child] physically has two working legs, severe autistic sensory exhaustion and hypotonia cause complete refusal after 50 meters, dropping to the floor.' },
    { step: 'mobility', qNum: 'Question 35', officialTitle: 'Does Walking Cause Severe Discomfort or Pain?', component: 'Mobility Criteria', pitfall: 'Saying No because they lack physical joint injuries.', guidance: 'Sensory overload causes severe somatic pain, extreme muscle tension, and exhaustion.', buzzwords: 'Somatic pain from sensory exhaustion, Physiological muscle fatigue.', exampleASD: 'Sensory bombardment outdoors (traffic, crowds) triggers intense somatic muscle tension; [Child] cries in severe physical pain and distress after minutes.' },
    { step: 'mobility', qNum: 'Question 36', officialTitle: 'How Far Can the Child Walk Before Stopping?', component: 'Distance Benchmark', pitfall: 'Stating a distance based on an exceptionally good day.', guidance: 'State realistic distance before meltdown or shutdown occurs on an average day.', buzzwords: 'Cannot reliably walk further than 40-50 meters, Rapid onset of sensory exhaustion.', exampleASD: '[Child] cannot walk reliably further than 40-50 meters outdoors before sensory overload causes complete refusal and dropping as dead-weight.' },
    { step: 'mobility', qNum: 'Question 37', officialTitle: 'How Long Does it Take to Walk That Distance?', component: 'Walking Pace', pitfall: 'Ignoring toe-walking halts and sensory freezes.', guidance: 'Explain that the pace is exceptionally slow, interrupted by freezes and pacing.', buzzwords: 'Halting erratic pace, Frequent sensory freezes, Abnormally slow.', exampleASD: 'Pace is exceptionally slow; [Child] freezes at drain covers or surface transitions, taking 15 minutes to cover 50 meters.' },
    { step: 'mobility', qNum: 'Question 38', officialTitle: 'Does the Child Walk in an Unnatural, Clumsy or Dangerous Way?', component: 'Gait & Coordination', pitfall: 'Assuming clumsy walking is normal.', guidance: 'Detail sensory toe-walking, dyspraxia, poor depth perception, and tripping.', buzzwords: 'Dyspraxic gait, Persistent sensory toe-walking, Frequent tripping and falling.', exampleASD: '[Child] walks on their tiptoes due to sensory defensiveness; poor balance and spatial awareness cause them to trip and fall 8-10 times weekly.' },
    { step: 'mobility', qNum: 'Question 39', officialTitle: 'Is Walking Dangerous to the Child\'s Health?', component: 'Danger Test', pitfall: 'Failing to link uncoordinated walking with street injury.', guidance: 'Explain that sudden meltdowns and falls on pavements cause immediate injury.', buzzwords: 'Acute danger of physical injury, High fall risk on concrete surfaces.', exampleASD: 'Walking outdoors is hazardous; sudden sensory meltdowns cause [Child] to throw themselves onto concrete pavements, risking head injuries.' },
    { step: 'mobility', qNum: 'Question 40', officialTitle: 'Does Walking Cause Severe Mental or Physical Distress?', component: 'Distress Test', pitfall: 'Downplaying meltdowns as bad moods.', guidance: 'Explain that sensory overload outdoors triggers genuine physiological panic.', buzzwords: 'Severe psychological panic, Overwhelming sensory distress.', exampleASD: 'Outdoor walking environments (sirens, barking dogs, bright lights) trigger genuine autistic terror, screaming, and uncontrollable flight panic.' },
    { step: 'mobility', qNum: 'Question 41', officialTitle: 'Does the Child Need Guidance or Supervision Outdoors?', component: 'Lower Rate Mobility (Supervision)', pitfall: 'Ticking that they can walk with verbal warnings.', guidance: 'Detail bolting, complete absence of road awareness, and need for a permanent wrist-hold.', buzzwords: 'Continuous 1-to-1 physical grip required, Total lack of road sense, High bolting risk.', exampleASD: '[Child] requires an uninterrupted 1-to-1 physical grip; they have zero road danger awareness and bolt blindly toward roads when overloaded.' },
    { step: 'mobility', qNum: 'Question 42', officialTitle: 'Does the Child Get Lost or Disoriented Outdoors?', component: 'Orientation', pitfall: 'Assuming an older child naturally recognizes home routes.', guidance: 'Detail total lack of directional awareness and panic in familiar locations.', buzzwords: 'Severe environmental disorientation, Inability to recognize familiar landmarks.', exampleASD: 'Becomes instantly disoriented even on our home street; cannot identify familiar houses and enters states of acute panic if physical contact is broken.' },
    { step: 'mobility', qNum: 'Question 43', officialTitle: 'Does the Child Behave Unpredictably Outdoors?', component: 'Behavioral Volatility', pitfall: 'Omitting flight and shutdown reactions.', guidance: 'Detail sudden dropping, bolting toward special interests, or public meltdowns.', buzzwords: 'Unpredictable flight reaction, Sudden dead-weight collapse, Elopement.', exampleASD: 'Prone to sudden elopement toward water or bright signs, or collapsing as dead-weight in the street, requiring immediate physical lifting.' },
    { step: 'mobility', qNum: 'Question 44', officialTitle: 'Can the Child Use Public Buses or Trains?', component: 'Transport Barriers', pitfall: 'Assuming public transit is manageable.', guidance: 'Detail how engine noise, vibrations, and strangers trigger acute meltdowns.', buzzwords: 'Sensory barrier to public transport, Panic in enclosed crowded spaces.', exampleASD: 'Public transport is impossible; engine noise, vibrating seats, and close passenger proximity trigger instant screaming sensory meltdowns.' },
    { step: 'mobility', qNum: 'Question 45', officialTitle: 'Does the Child Need Physical Help Getting On/Off Transport?', component: 'Transport Handling', pitfall: 'Leaving blank.', guidance: 'Detail physical handling required on transport steps during panic.', buzzwords: 'Requires physical lifting and containment on transport steps.', exampleASD: 'Must be physically carried onto transport steps due to motor dyspraxia and panic-induced physical freezes.' },
    { step: 'mobility', qNum: 'Question 46', officialTitle: 'Problems Travelling in Cars or Taxis', component: 'Vehicle Safety', pitfall: 'Saying car travel is fine when meltdowns occur inside.', guidance: 'Detail unbuckling seatbelts, kicking windows, and sensory distress.', buzzwords: 'Attempting to unbuckle seatbelts while vehicle is moving, Severe vehicular distress.', exampleASD: '[Child] panics in cars, screaming and attempting to unbuckle seatbelts due to tactile restraint aversion, creating acute driving hazards.' },
    { step: 'mobility', qNum: 'Question 47', officialTitle: 'Does the Child Need Special Car Seats or Restraints?', component: 'Vehicle Safety Equipment', pitfall: 'Not mentioning anti-escape clips.', guidance: 'Detail specialized 5-point harnesses, chest clips, and window child locks.', buzzwords: 'Anti-escape buckle guards, Specialist 5-point harness car seat.', exampleASD: 'Requires a specialist car seat fitted with anti-escape chest clips to prevent unbuckling; child locks must remain permanently engaged.' },
    { step: 'mobility', qNum: 'Question 48', officialTitle: 'Can the Child Cross Roads Safely?', component: 'Road Safety Deficit', pitfall: 'Saying Yes because they hold hands when forced.', guidance: 'Explain that left unattended, they have zero comprehension of moving vehicles.', buzzwords: 'Total absence of road danger perception, Steps into moving traffic.', exampleASD: 'Has zero concept of road safety; perceives roads literally as open flat space and will walk directly in front of moving vehicles without looking.' },
    { step: 'mobility', qNum: 'Question 49', officialTitle: 'Does the Child Freeze or Panic Near Traffic?', component: 'Sensory Traffic Panic', pitfall: 'Leaving blank.', guidance: 'Detail freezing on crossings when loud trucks pass.', buzzwords: 'Sensory freeze response on pedestrian crossings, Traffic siren terror.', exampleASD: 'Loud vehicles or sirens cause [Child] to drop to their knees and freeze on pedestrian crossings in absolute terror.' },
    { step: 'mobility', qNum: 'Question 50', officialTitle: 'Can the Child Cope with Changes to Outdoor Routes?', component: 'Cognitive Rigidity', pitfall: 'Downplaying detour meltdowns.', guidance: 'Explain that route changes break cognitive schemas, triggering multi-hour meltdowns.', buzzwords: 'Autistic cognitive rigidity, Severe distress from unexpected detours.', exampleASD: 'Any detour or route change triggers catastrophic distress; [Child] screams, drops to the pavement, and refuses to move forward.' },
    { step: 'mobility', qNum: 'Question 51', officialTitle: 'Does the Child Need a Specialist Buggy or Stroller?', component: 'Mobility Equipment', pitfall: 'Assuming specialist buggies are just normal prams.', guidance: 'State that specialist buggies are medical safety aids for children beyond pram age.', buzzwords: 'Specialist disability stroller, Prescribed mobility containment buggy.', exampleASD: 'Must be transported in a specialist disability buggy to provide sensory containment and prevent impulsive bolting into traffic.' },
    { step: 'mobility', qNum: 'Question 52', officialTitle: 'How Does Bad Weather Affect Mobility Outdoors?', component: 'Tactile Weather Impact', pitfall: 'Ignoring sensory weather sensitivity.', guidance: 'Explain how rain, cold, or wind intensifies tactile defensiveness, halting movement.', buzzwords: 'Rain on skin triggers tactile agony, Wind noise amplifies sensory overload.', exampleASD: 'Raindrops touching the skin cause agonizing tactile distress; [Child] screams and completely refuses to walk.' },
    { step: 'mobility', qNum: 'Question 53', officialTitle: 'Any Other Outdoor Mobility Difficulties?', component: 'Mobility Summary', pitfall: 'Leaving mobility summary blank.', guidance: 'Summarize the exhausting necessity of constant physical containment outdoors.', buzzwords: 'Comprehensive outdoor mobility restriction, Exhausting physical supervision load.', exampleASD: 'Outdoor mobility requires unrelenting physical vigilance and containment; independent walking is impossible due to sensory panic and elopement.' },

    // ==========================================
    // PART 3: DAYTIME CARE NEEDS (Q54 - Q62)
    // ==========================================
    { step: 'daycare', qNum: 'Question 54', officialTitle: 'Getting In and Out of Bed / Settling in Bed', component: 'Morning Transition', pitfall: 'Saying they wake up independently without noting transition battles.', guidance: 'Detail profound sleep inertia, executive paralysis, and 45+ minutes of physical coaxing.', buzzwords: 'Profound sleep inertia, Executive transition paralysis, 40+ minutes physical coaxing.', exampleASD: '[Child] suffers profound sleep inertia and transition anxiety; requires 45 minutes of quiet co-regulation and touch to leave bed.' },
    { step: 'daycare', qNum: 'Question 55', officialTitle: 'Toileting Needs and Managing Continence', component: 'Personal Care (Toileting)', pitfall: 'Calling accidents laziness.', guidance: 'Explain impaired interoception (no urge awareness) and tactile aversion to wiping.', buzzwords: 'Impaired interoception (no urge awareness), Tactile defensiveness to wiping, Scheduled prompts.', exampleASD: '[Child] has impaired interoception and cannot sense bladder fullness until overflow occurs; requires scheduled 60-minute prompts and assistance wiping.' },
    { step: 'daycare', qNum: 'Question 56', officialTitle: 'Daytime Continence Accidents & Clean-Up', component: 'Incontinence Load', pitfall: 'Under-reporting weekly wetting or soiling frequency.', guidance: 'State the exact weekly accident frequency and parental cleanup burden.', buzzwords: 'Regular daytime soiling/wetting, Complete parental clothing strip and wash.', exampleASD: 'Experiences 3-5 daytime soiling accidents weekly due to absent interoceptive awareness, requiring full adult clean-up and clothing changes.' },
    { step: 'daycare', qNum: 'Question 57', officialTitle: 'Washing, Bathing, Showering and Oral Hygiene', component: 'Personal Care (Hygiene)', pitfall: 'Writing they wash themselves because they splash water.', guidance: 'Detail sensory pain from water on face, scald hazards, and teeth brushing gag reflex.', buzzwords: 'Tactile defensiveness to water spray, Oral hypersensitivity gag reflex, Scald hazard.', exampleASD: 'Bathing is an agonizing ordeal; water on the face triggers panic. Teeth brushing induces retching; requires complete parental washing and supervision.' },
    { step: 'daycare', qNum: 'Question 58', officialTitle: 'Dressing and Undressing During the Day', component: 'Personal Care (Dressing)', pitfall: 'Ticking they dress independently if they can pull on loose socks.', guidance: 'Detail tag removal, seam inversion, and inability to sequence clothing items.', buzzwords: 'Tactile defensiveness to clothing seams, Multi-step sequencing failure, 1:1 adult dressing.', exampleASD: 'All clothing tags must be removed and seams inverted due to tactile defensiveness; [Child] cannot sequence garments and requires full adult dressing.' },
    { step: 'daycare', qNum: 'Question 59', officialTitle: 'Eating and Drinking', component: 'Personal Care (Feeding)', pitfall: 'Assuming feeding questions only apply if tube-fed.', guidance: 'Detail ARFID, restricted beige foods, food pocketing choking hazards, and coaxing.', buzzwords: 'ARFID sensory food aversion, Food pocketing choking hazard, Intensive mealtime coaxing.', exampleASD: 'Severe ARFID restricts diet to 3 beige textures. Pockets food in cheeks for 30 minutes, creating an acute choking hazard requiring 1-to-1 monitoring.' },
    { step: 'daycare', qNum: 'Question 60', officialTitle: 'Taking Medication or Healthcare Treatments', component: 'Medical Oversight', pitfall: 'Leaving blank if they refuse pills.', guidance: 'Explain that extreme sensory taste defensiveness requires hiding medicine in purees.', buzzwords: 'Extreme sensory taste defensiveness, Requires disguised medication administration.', exampleASD: 'Extreme oral sensitivity causes violent spitting of medicine; requires liquid disguise in purees and 30 minutes of parental coaxing.' },
    { step: 'daycare', qNum: 'Question 61', officialTitle: 'Communicating Basic Daytime Needs', component: 'Communication Barrier', pitfall: 'Assuming talking a lot means functional communication.', guidance: 'Detail situational mutism, echolalia, and inability to report physical pain or thirst.', buzzwords: 'Situational mutism under stress, Inability to articulate pain or physical needs.', exampleASD: 'When overwhelmed, [Child] loses speech entirely (situational mutism) and cannot express hunger, thirst, or pain, requiring parents to interpret non-verbal signs.' },
    { step: 'daycare', qNum: 'Question 62', officialTitle: 'Any Other Daytime Care Needs?', component: 'Daytime Summary', pitfall: 'Leaving daytime summary blank.', guidance: 'Summarize the constant, unrelenting nature of daytime supervision and co-regulation.', buzzwords: 'Unrelenting daytime care burden substantially exceeding neurotypical peer baseline.', exampleASD: 'Every waking moment requires continuous 1-to-1 scaffolding, sensory diet management, and emotional co-regulation substantially in excess of a peer.' },

    // ==========================================
    // PART 4: SAFETY & DEVELOPMENT (Q63 - Q72)
    // ==========================================
    { step: 'safety', qNum: 'Question 63', officialTitle: 'Supervision Indoors to Avoid Substantial Danger', component: 'Substantial Danger Test', pitfall: 'Failing to explain what happens if your back is turned for 2 minutes.', guidance: 'Detail climbing worktops, turning on cookers, and domestic hazard deficits.', buzzwords: 'Continual supervision throughout the day to avoid substantial danger, Zero hazard perception.', exampleASD: 'Cannot be left unmonitored for 60 seconds; climbs high kitchen units, turns on gas hobs, and scales stairgates with zero hazard awareness.' },
    { step: 'safety', qNum: 'Question 64', officialTitle: 'Dangerous Indoor Behaviors and Destruction', component: 'Domestic Safety', pitfall: 'Downplaying property damage as accidents.', guidance: 'Detail throwing heavy objects, breaking glass, and damaging fixtures during meltdowns.', buzzwords: 'Explosive property destruction during meltdowns, Shattering objects.', exampleASD: 'During sensory meltdowns, [Child] throws hard items, kicks doors off hinges, and shatters glass in panic, creating acute household hazards.' },
    { step: 'safety', qNum: 'Question 65', officialTitle: 'Awareness of Common Household Hazards', component: 'Hazard Deficit', pitfall: 'Assuming an older child knows fire is dangerous.', guidance: 'Explain total absence of cause-and-effect thinking regarding heat, electricity, and knives.', buzzwords: 'Complete hazard awareness deficit, Inability to foresee dangerous consequences.', exampleASD: 'Has zero concept of heat or fire; will reach directly onto glowing hot cooker rings or touch bare electrical cables without hesitation.' },
    { step: 'safety', qNum: 'Question 66', officialTitle: 'Communication and Social Vulnerability', component: 'Social Exploitation', pitfall: 'Saying they communicate fine because they talk endlessly about special interests.', guidance: 'Detail hyper-literal thinking, lack of stranger danger discernment, and social exploitation.', buzzwords: 'Hyper-literal interpretation, Zero stranger danger awareness, Highly vulnerable.', exampleASD: 'Interprets language 100% literally; would willingly leave with strangers who mentioned autism special interests, possessing zero stranger danger awareness.' },
    { step: 'safety', qNum: 'Question 67', officialTitle: 'Understanding Intentions of Others', component: 'Social Understanding', pitfall: 'Leaving blank.', guidance: 'Explain inability to read facial expressions, detect sarcasm, or realize they are being manipulated.', buzzwords: 'Inability to detect deceit or malicious intent, Profound social naivety.', exampleASD: 'Cannot read facial expressions or tone; takes malicious teasing as genuine friendship, making them acutely vulnerable to peer manipulation.' },
    { step: 'safety', qNum: 'Question 68', officialTitle: 'Behavioral Disturbance and Outbursts', component: 'Behavioral Oversight', pitfall: 'Calling meltdowns mere tantrums.', guidance: 'Detail explosive sensory overloads lasting 45-90 minutes where reasoning is impossible.', buzzwords: 'Severe neurological meltdown, Complete loss of emotional self-regulation.', exampleASD: 'Sensory overload triggers 60-90 minute fight-or-flight meltdowns involving screaming, thrashing, and complete loss of cognitive self-regulation.' },
    { step: 'safety', qNum: 'Question 69', officialTitle: 'Does the Child Harm Themselves?', component: 'Self-Harm & Injury', pitfall: 'Hiding head-banging or biting out of shame.', guidance: 'Detail self-injurious actions during sensory overloads (head-banging on tile floors, skin-biting).', buzzwords: 'Self-injurious head-banging on hard surfaces, Severe skin biting during meltdowns.', exampleASD: 'Violently bangs head against tiled floors and bites own forearms until bruised and bleeding during peak sensory meltdowns.' },
    { step: 'safety', qNum: 'Question 70', officialTitle: 'Does the Child Require Physical Intervention?', component: 'Physical Restraint', pitfall: 'Leaving blank out of embarrassment.', guidance: 'Detail holding the child to prevent severe head trauma, road-running, or injury.', buzzwords: 'Requires gentle physical containment / blocking to prevent catastrophic self-harm.', exampleASD: 'Parents must use gentle physical holding techniques to cushion head blows and prevent skull fractures during violent autistic meltdowns.' },
    { step: 'safety', qNum: 'Question 71', officialTitle: 'PICA or Mouthing Inappropriate Objects', component: 'PICA Risk', pitfall: 'Assuming mouthing stops in infancy.', guidance: 'Detail chewing and swallowing batteries, plastics, cables, clothing, or foam.', buzzwords: 'PICA behavior mouthing non-food items, Acute poisoning and bowel obstruction risk.', exampleASD: 'Displays severe PICA seeking; chews through foam mattresses, plastics, and paper, creating acute poisoning and obstruction risks.' },
    { step: 'safety', qNum: 'Question 72', officialTitle: 'Any Other Safety or Developmental Needs?', component: 'Safety Summary', pitfall: 'Leaving safety summary blank.', guidance: 'Summarize the exhausting necessity of 100% continuous line-of-sight supervision indoors.', buzzwords: 'Exhausting requirement for continuous line-of-sight safety supervision.', exampleASD: 'The combination of sensory seeking, self-harm, and zero danger awareness requires relentless 1-to-1 line-of-sight supervision at all times.' },

    // ==========================================
    // PART 5: NIGHT-TIME CARE & EXTRA INFORMATION (Q73 - Q84)
    // ==========================================
    { step: 'night', qNum: 'Question 73', officialTitle: 'Help Needed During the Night (11pm to 7am)', component: 'Higher Rate Care Trigger', pitfall: 'Thinking night waking is just ordinary bad sleep.', guidance: 'Must wake 2-3+ times OR require attention for at least 20 minutes to qualify for Higher Rate Care.', buzzwords: 'Delayed circadian sleep phase, Nocturnal hyperarousal, Prolonged night waking (45+ mins).', exampleASD: '[Child] wakes 2-3 times every night due to circadian sleep failure; requires 45 minutes of physical co-regulation and settling each time.' },
    { step: 'night', qNum: 'Question 74', officialTitle: 'How Many Times Does the Child Wake Up?', component: 'Night Waking Frequency', pitfall: 'Guessing instead of logging actual interruptions.', guidance: 'State the exact nightly frequency (e.g. 2 to 4 times every single night).', buzzwords: 'Consistently wakes 3-4 times every single night without exception.', exampleASD: 'Wakes on average 3 to 4 times every night in an anxious, dysregulated state, unable to self-settle without direct adult intervention.' },
    { step: 'night', qNum: 'Question 75', officialTitle: 'How Long Does Each Waking Episode Last?', component: 'Night Duration', pitfall: 'Claiming they settle in 5 minutes.', guidance: 'Explain that calming an autistic nervous system at 3 AM takes 30 to 50 minutes.', buzzwords: 'Each waking episode lasts 35 to 50 minutes of active parental settling.', exampleASD: 'Each waking episode requires 40-50 minutes of deep touch pressure, sensory soothing, and parental co-regulation to restore calm.' },
    { step: 'night', qNum: 'Question 76', officialTitle: 'What Attention Does the Child Need at Night?', component: 'Night Care Actions', pitfall: 'Saying you just hand them a drink.', guidance: 'Detail preventing nighttime wandering, deep touch massage, and guarding against falls.', buzzwords: 'Intensive nocturnal co-regulation, Preventing dangerous unsupervised night wandering.', exampleASD: 'I must sit physically with [Child], block attempts to open windows or wander the house in the dark, and apply firm deep touch pressure.' },
    { step: 'night', qNum: 'Question 77', officialTitle: 'Does the Child Wet or Soil the Bed at Night?', component: 'Nocturnal Enuresis', pitfall: 'Calling nighttime bedwetting normal for an older child.', guidance: 'Detail nocturnal enuresis, lack of wake-up reflex, and pull-up usage.', buzzwords: 'Severe nocturnal enuresis, Absent bladder wake-up reflex, Heavy pull-up leaks.', exampleASD: '[Child] experiences nightly nocturnal enuresis; deep sleep architecture prevents bladder wake-up signals, requiring pull-ups and waterproof bedding.' },
    { step: 'night', qNum: 'Question 78', officialTitle: 'How Often Do Nighttime Bedwetting Accidents Occur?', component: 'Accident Frequency', pitfall: 'Minimizing accidents as rare.', guidance: 'State exact weekly frequency (e.g. 6 to 7 nights per week).', buzzwords: 'Accidents occur 7 nights a week, Constant nocturnal laundry burden.', exampleASD: 'Bedwetting occurs on 7 out of 7 nights every week without exception, requiring pull-ups and complete sheet changes.' },
    { step: 'night', qNum: 'Question 79', officialTitle: 'What Help is Needed with Nighttime Incontinence?', component: 'Accident Clean-Up', pitfall: 'Saying they change themselves.', guidance: 'Detail waking up, stripping wet sheets, washing the child, and changing pajamas in the dark.', buzzwords: 'Full middle-of-the-night bed stripping, washing child, and pajama changes.', exampleASD: 'I must wake, strip saturated sheets, wash the child\'s skin to prevent sensory irritation, and redress them in fresh clothes at 3 AM.' },
    { step: 'night', qNum: 'Question 80', officialTitle: 'Seizures, Fits or Medical Episodes at Night', component: 'Nocturnal Medical Episodes', pitfall: 'Confusing bad dreams with clinical seizures.', guidance: 'State none if no epilepsy, or detail nocturnal panic, sensory night terrors, and breath holding.', buzzwords: 'Nocturnal sensory panic episodes, Violent night terrors.', exampleASD: 'No clinical epilepsy; however, [Child] experiences severe sensory night terrors involving thrashing and screaming, requiring parental containment.' },
    { step: 'night', qNum: 'Question 81', officialTitle: 'Does the Child Need Medication at Night?', component: 'Night Medication', pitfall: 'Leaving blank if given at bedtime.', guidance: 'Detail melatonin administration, second doses, or calming remedies given during night wakings.', buzzwords: 'Administering prescribed melatonin and sleep support medications.', exampleASD: 'Administer prescribed melatonin and soothing creams during midnight waking episodes to restore sleep under pediatric guidance.' },
    { step: 'night', qNum: 'Question 82', officialTitle: 'Does Anyone Stay Awake to Watch Over the Child at Night?', component: 'Night Watcher Criteria', pitfall: 'Saying No because you sleep in your own bed (even though you are awake half the night).', guidance: 'Explain that broken sleep and constant monitoring amount to an active night watch.', buzzwords: 'Broken sleep pattern constituting an active night vigil, Constant hypervigilance.', exampleASD: 'While in my own bed, my sleep is completely fragmented; I am effectively on an active night watch waking 3 times to prevent danger.' },
    { step: 'night', qNum: 'Question 83', officialTitle: 'Any Other Special Nighttime Needs?', component: 'Night Adaptations', pitfall: 'Leaving blank.', guidance: 'Detail bedroom door alarms, specialized high-security window latches, and monitor cameras.', buzzwords: 'Specialized alarmed door chimes, Window restrictors, Video baby monitor oversight.', exampleASD: 'We have installed alarmed door chimes and window restrictors to prevent [Child] escaping the room unannounced in the dark.' },
    { step: 'night', qNum: 'Question 84', officialTitle: 'Extra Information (24-Hour Master Summary Statement)', component: 'Final Impact Statement', pitfall: 'Leaving this blank or writing a single brief sentence.', guidance: 'Summarize the relentless, exhausting 24-hour caregiver burden and contrast against a neurotypical child.', buzzwords: 'Substantially in excess of a child of the same age, Unrelenting 24-hour care burden, Severe cumulative impact.', exampleASD: 'In summary, [Child] requires unrelenting 24-hour care, physical protection, and sensory co-regulation substantially in excess of a neurotypical peer. Every basic function—waking, dressing, feeding, walking, and sleeping—demands intensive adult intervention to prevent severe harm.' }
];