window.dlaMasterData = [
    // ==========================================
    // PART 1: OVERVIEW & HEALTH CONDITIONS (Q1 - Q33)
    // ==========================================
    { step: 'part1', qNum: 'Question 1', officialTitle: 'Child Full Name', component: 'Eligibility Baseline', pitfall: 'Using an informal nickname rather than the child\'s full legal name.', guidance: 'Must match official birth certificate and Child Benefit records.', buzzwords: 'Legal identity verification.', exampleASD: '[Child] official registered name matches birth certificate and clinical NHS records exactly.' },
    { step: 'part1', qNum: 'Question 2', officialTitle: 'Child Date of Birth', component: 'Eligibility Baseline', pitfall: 'Misjudging statutory age qualifying rules.', guidance: 'Establishes age criteria for care (birth+) and mobility (higher at 3+, lower at 5+).', buzzwords: 'Statutory child age criteria.', exampleASD: 'Born [DOB], qualifying under standard statutory child disability allowance criteria.' },
    { step: 'part1', qNum: 'Question 3', officialTitle: 'Child Residential Address', component: 'Residency Baseline', pitfall: 'Failing to state primary permanent residence.', guidance: 'Confirm where the child permanently lives and receives care.', buzzwords: 'Permanent UK habitual residence.', exampleASD: 'Resides permanently at home with primary family caregiver providing daily care.' },
    { step: 'part1', qNum: 'Question 4', officialTitle: 'Who is Filling in this Form?', component: 'Guardian Details', pitfall: 'Not specifying full parental responsibility.', guidance: 'Confirm legal parental responsibility and day-to-day caring role.', buzzwords: 'Primary legal parent, 24-hour caregiver.', exampleASD: 'Completed by primary parent providing round-the-clock supervision and hands-on care for [Child].' },
    { step: 'part1', qNum: 'Question 5', officialTitle: 'Does the Child Live with You?', component: 'Residency Test', pitfall: 'Omitting custody splits or residential care stays.', guidance: 'Confirm full-time 365-day care at home.', buzzwords: 'Full-time parental care at home.', exampleASD: 'Lives with claimant full-time under continuous daily parental care and management.' },
    { step: 'part1', qNum: 'Question 6', officialTitle: 'Nationality and Immigration Status', component: 'Residency Test', pitfall: 'Leaving UK residency gaps unexplained.', guidance: 'Confirms UK habitual residence test compliance.', buzzwords: 'Habitual UK resident.', exampleASD: 'UK citizen habitually resident in the UK meeting all statutory residency rules.' },
    { step: 'part1', qNum: 'Question 7', officialTitle: 'Does the Child Attend School or Nursery?', component: 'Educational Baseline', pitfall: 'Stating standard full-time attendance if they have reduced hours or masking burnout.', guidance: 'Detail school setting, reduced timetables, or Emotionally-Based School Avoidance.', buzzwords: 'SEND Support Register, reduced timetable, masking collapse at home.', exampleASD: 'Attends mainstream school on SEND register. Holds everything in while at school (masking), resulting in severe physical distress and violent meltdowns the minute they walk through the door at home.' },
    { step: 'part1', qNum: 'Question 8', officialTitle: 'Name and Address of School', component: 'Educational Evidence', pitfall: 'Giving generic office details.', guidance: 'Provide campus address and direct SEND department contacts.', buzzwords: 'Designated educational placement.', exampleASD: 'Enrolled at [School Name], under direct daily support from the school SEND team.' },
    { step: 'part1', qNum: 'Question 9', officialTitle: 'Who Knows the Child Best at School?', component: 'Educational Contact', pitfall: 'Listing the headteacher instead of classroom staff.', guidance: 'Name the specific SENCO or 1-to-1 Teaching Assistant who manages meltdowns.', buzzwords: 'Special Educational Needs Coordinator (SENCO), 1-to-1 Teaching Assistant.', exampleASD: '[SENCO Name] and dedicated 1-to-1 Teaching Assistant who provide constant hands-on reassurance and supervise daily transitions.' },
    { step: 'part1', qNum: 'Question 10', officialTitle: 'Does the Child Receive Extra Educational Help?', component: 'SEN Provision', pitfall: 'Downplaying informal accommodations.', guidance: 'Detail workstation modifications, ear defenders in class, and visual schedules.', buzzwords: 'Visual timetable, 1-to-1 constant prompts, ear defenders, sensory timeout space.', exampleASD: 'Cannot follow standard instructions without an adult standing over them to break tasks into single steps. Uses ear defenders for assemblies and lunch halls, and requires frequent breaks in a quiet space.' },
    { step: 'part1', qNum: 'Question 11', officialTitle: 'Does the Child Have an EHCP or IEP?', component: 'Statutory SEN', pitfall: 'Ticking No while an EHCP assessment is underway.', guidance: 'State active EHCP status or active statutory assessment in progress.', buzzwords: 'Statutory EHCP in place / in assessment, Section F provision.', exampleASD: 'Maintains an active EHCP confirming severe difficulties with communication, sensory processing, and social understanding requiring continuous adult supervision.' },
    { step: 'part1', qNum: 'Question 12', officialTitle: 'Does the Child Stay at Boarding School?', component: 'Institutional Rule', pitfall: 'Failing to confirm standard home return.', guidance: 'Confirm child lives at home full-time.', buzzwords: 'Day-pupil returning home daily.', exampleASD: 'Day-pupil only; returns home every afternoon requiring multiple hours of quiet co-regulation and hands-on parental care.' },
    { step: 'part1', qNum: 'Question 13', officialTitle: 'Does the Child Attend Clubs or Daycare?', component: 'Social Functioning', pitfall: 'Writing No without explaining the sensory reason.', guidance: 'Explain that noisy group environments cause severe sensory meltdowns.', buzzwords: 'Cannot attend clubs, severe distress from noise and crowds, 1-to-1 support required.', exampleASD: 'Cannot attend any clubs, sports, or after-school activities. The noise, open spaces, and unpredictability cause sheer panic, screaming, and running away.' },
    { step: 'part1', qNum: 'Question 14', officialTitle: 'Does Anyone Else Help Look After the Child?', component: 'Care Network', pitfall: 'Downplaying the intense specialized nature of the care.', guidance: 'Clarify that relatives cannot manage the child\'s autistic meltdowns or safety risks.', buzzwords: 'Cannot be safely left with relatives, specialist parent-only care.', exampleASD: 'Cannot be left with grandparents or babysitters. Family members cannot manage the physical distress, meltdowns, or constant bolting risks safely.' },
    { step: 'part1', qNum: 'Question 15', officialTitle: 'Does the Child Receive Help from Social Services?', component: 'Social Care', pitfall: 'Thinking lack of social services invalidates medical needs.', guidance: 'State Early Help, Disabled Children\'s Team, or confirm all care is parental.', buzzwords: 'Early Help Plan, intensive parental care at home.', exampleASD: 'Supported via Early Help / all intensive daily supervision and hands-on care is provided entirely by parents at home.' },
    { step: 'part1', qNum: 'Question 16', officialTitle: 'Is the Child in Local Authority Care?', component: 'Care Order', pitfall: 'Misinterpreting parental legal responsibility.', guidance: 'Confirm full private parental custody.', buzzwords: 'Full private parental responsibility.', exampleASD: 'Resides permanently with parents under full private parental responsibility.' },
    { step: 'part1', qNum: 'Question 17', officialTitle: 'Is the Child Currently in Hospital or Residential Care?', component: 'Institutional Test', pitfall: 'Leaving blank.', guidance: 'Confirm the child is currently cared for at home.', buzzwords: 'Home-based care.', exampleASD: 'Not in hospital; residing permanently at home under continuous family care.' },
    { step: 'part1', qNum: 'Question 18', officialTitle: 'Hospital Admission Dates (If Applicable)', component: 'Institutional Test', pitfall: 'N/A confusion.', guidance: 'Mark as Not Applicable.', buzzwords: 'Not applicable.', exampleASD: 'Not applicable - cared for at home.' },
    { step: 'part1', qNum: 'Question 19', officialTitle: 'Who Pays for Hospital / Care Costs?', component: 'Funding Rule', pitfall: 'N/A confusion.', guidance: 'Mark Not Applicable.', buzzwords: 'Not applicable.', exampleASD: 'Not applicable.' },
    { step: 'part1', qNum: 'Question 20', officialTitle: 'Immigration Control Restrictions', component: 'Residency Rule', pitfall: 'Incorrect declaration.', guidance: 'Confirm UK citizen exemption.', buzzwords: 'Exempt from immigration control.', exampleASD: 'Full UK citizen exempt from immigration control.' },
    { step: 'part1', qNum: 'Question 21', officialTitle: 'Other Benefits Received for the Child', component: 'Benefit Baseline', pitfall: 'Omitting standard benefits.', guidance: 'List standard Child Benefit.', buzzwords: 'Child Benefit.', exampleASD: 'Receives standard UK Child Benefit.' },
    { step: 'part1', qNum: 'Question 22', officialTitle: 'Previous DLA Claim History', component: 'Claim History', pitfall: 'Omitting past claim details.', guidance: 'Confirm initial claim or review status.', buzzwords: 'Initial application, care needs substantially in excess.', exampleASD: 'Initial application due to escalating daily care, constant safety supervision, and mobility difficulties.' },
    { step: 'part1', qNum: 'Question 23', officialTitle: 'What Illnesses, Disabilities or Conditions Does the Child Have?', component: 'Eligibility Baseline', pitfall: 'Waiting for a formal diagnostic report before applying.', guidance: 'Formal diagnosis is not required. State autism under clinical investigation.', buzzwords: 'Autism Spectrum Disorder, Sensory Processing Disorder, severe speech delay.', exampleASD: '[Child] is undergoing assessment for Autism Spectrum Disorder (ASD) and Sensory Processing difficulties, resulting in severe communication deficits, zero hazard awareness, and frequent daily meltdowns.' },
    { step: 'part1', qNum: 'Question 24', officialTitle: 'What Medications Does the Child Take?', component: 'Medical Management', pitfall: 'Leaving blank if unmedicated.', guidance: 'List prescribed melatonin, laxatives, and daily sensory diet routines.', buzzwords: 'Prescribed melatonin for severe sleep onset failure, daily laxatives.', exampleASD: 'Prescribed daily melatonin to settle severe sleep disturbance; requires daily laxatives due to sensory withholding.' },
    { step: 'part1', qNum: 'Question 25', officialTitle: 'Treatments, Therapies and Interventions', component: 'Clinical Input', pitfall: 'Omitting home-based therapies.', guidance: 'Detail Occupational Therapy (OT), joint compressions, and sensory decompression spaces.', buzzwords: 'Occupational Therapy sensory routine, visual boards, deep pressure calming.', exampleASD: 'We carry out daily home sensory routines recommended by OT: deep pressure massage, weighted blankets, visual boards, and quiet spaces to prevent head-banging and meltdowns.' },
    { step: 'part1', qNum: 'Question 26', officialTitle: 'GP Name and Surgery Details', component: 'Medical Contact', pitfall: 'Incomplete surgery contact details.', guidance: 'Provide full practice name, address, and phone number.', buzzwords: 'Registered GP surgery.', exampleASD: 'Dr [Name], [Surgery Address], holding complete medical history and pediatric referrals.' },
    { step: 'part1', qNum: 'Question 27', officialTitle: 'Hospital Consultant or Paediatrician Details', component: 'Specialist Evidence', pitfall: 'Listing the hospital without naming the consultant.', guidance: 'Name the specific Community Paediatrician conducting the assessment.', buzzwords: 'Consultant Community Paediatrician, Child Development Centre.', exampleASD: 'Dr [Name], Consultant Community Paediatrician at [Clinic], overseeing formal autism diagnostic assessments.' },
    { step: 'part1', qNum: 'Question 28', officialTitle: 'Educational Psychologist or SENCO Contact', component: 'Educational Evidence', pitfall: 'Leaving blank if reports are pending.', guidance: 'Provide contact details for the school SENCO or Educational Psychologist.', buzzwords: 'School SENCO, Educational Psychologist.', exampleASD: '[SENCO Name], managing school sensory accommodations, 1-to-1 support, and daily visual prompts.' },
    { step: 'part1', qNum: 'Question 29', officialTitle: 'Other Therapists Involved in Care', component: 'Therapy Network', pitfall: 'Omitting Speech Therapists or Private OTs.', guidance: 'List every private or NHS Occupational Therapist, SALT, or CAMHS worker.', buzzwords: 'Speech and Language Therapist (SALT), Occupational Therapist (OT).', exampleASD: 'Speech and Language Therapist (SALT) for non-verbal communication and Occupational Therapist (OT) for severe sensory defensiveness.' },
    { step: 'part1', qNum: 'Question 30', officialTitle: 'Recent Medical Tests, Assessments or Reports', component: 'Clinical Reports', pitfall: 'Failing to mention clinical paperwork attached.', guidance: 'List developmental assessments, ADOS-2 reports, and sensory profile scores.', buzzwords: 'ADOS-2 assessment report, OT Sensory Profile, Pediatric review.', exampleASD: 'Attached: ADOS-2 assessment summary, OT Sensory Profile showing extreme sensory reactivity, and School SEND support plan.' },
    { step: 'part1', qNum: 'Question 31', officialTitle: 'Upcoming Appointments or Admissions', component: 'Active Pathway', pitfall: 'Leaving blank while waiting for clinic dates.', guidance: 'Confirm child is on active NHS pediatric clinic waiting lists.', buzzwords: 'Active pediatric neurodevelopmental waiting list.', exampleASD: 'Awaiting scheduled Multi-Disciplinary Neurodevelopmental clinic assessment and review appointments.' },
    { step: 'part1', qNum: 'Question 32', officialTitle: 'Special Aids, Equipment or Adaptations', component: 'Equipment Needs', pitfall: 'Writing None because the child does not use a wheelchair.', guidance: 'Detail ear defenders, chewelry, weighted blankets, visual timers, and bed rails.', buzzwords: 'Ear defenders, chewable pendants, weighted blanket, high safety door locks.', exampleASD: 'Uses noise-cancelling ear defenders, chewable silicone pendants, 3kg weighted blanket, visual timer boards, and high locks on external doors to prevent escaping.' },
    { step: 'part1', qNum: 'Question 33', officialTitle: 'Other Health Professionals Involved', component: 'Care Network', pitfall: 'Leaving blank.', guidance: 'List specialist health visitors or pediatric community nurses.', buzzwords: 'Specialist Health Visitor.', exampleASD: 'Supported by Specialist Health Visitor for developmental delays, extreme food refusal, and severe sleep disruption.' },

    // ==========================================
    // PART 2: OUTDOOR MOBILITY (Q34 - Q53)
    // ==========================================
    { step: 'mobility', qNum: 'Question 34', officialTitle: 'Can the Child Walk Outdoors on Familiar Routes Without Help?', component: 'Higher Rate Mobility (Walking Test)', pitfall: 'Assuming walking questions only count if paralyzed.', guidance: 'Explain that sensory overload, hypotonia, and autistic shutdowns halt walking.', buzzwords: 'Refuses to walk, drops to floor as dead weight, severe distress from outdoors.', exampleASD: 'Although physically able to walk, after roughly 40-50 metres outside [Child] becomes completely overwhelmed by street noises and visual input. They drop to the pavement as a dead weight, scream, and refuse to stand up or take another step.' },
    { step: 'mobility', qNum: 'Question 35', officialTitle: 'Does Walking Cause Severe Discomfort or Pain?', component: 'Mobility Criteria', pitfall: 'Saying No because they lack physical joint injuries.', guidance: 'Sensory overload causes severe somatic pain, extreme muscle tension, and exhaustion.', buzzwords: 'Severe distress, muscle stiffness, crying and screaming from walking.', exampleASD: 'Outdoor walking causes extreme physical tension and distress. Traffic noise and bright light overwhelm [Child] quickly; they clench their fists, cry hysterically, and hold their head in genuine agony after just a few minutes outside.' },
    { step: 'mobility', qNum: 'Question 36', officialTitle: 'How Far Can the Child Walk Before Stopping?', component: 'Distance Benchmark', pitfall: 'Stating a distance based on an exceptionally good day.', guidance: 'State realistic distance before meltdown or shutdown occurs on an average day.', buzzwords: 'Cannot walk more than 40-50 metres safely, stops completely.', exampleASD: '[Child] cannot walk more than roughly 40 to 50 metres before freezing, dropping to the floor, or trying to bolt into danger.' },
    { step: 'mobility', qNum: 'Question 37', officialTitle: 'How Long Does it Take to Walk That Distance?', component: 'Walking Pace', pitfall: 'Ignoring toe-walking halts and sensory freezes.', guidance: 'Explain that the pace is exceptionally slow, interrupted by freezes and pacing.', buzzwords: 'Extremely slow, halts every few yards, takes 15-20 minutes for short distances.', exampleASD: 'Progress is extremely slow. [Child] stops and freezes at every drain cover, line on the pavement, or loud noise, taking 15 to 20 minutes just to move 50 metres.' },
    { step: 'mobility', qNum: 'Question 38', officialTitle: 'Does the Child Walk in an Unnatural, Clumsy or Dangerous Way?', component: 'Gait & Coordination', pitfall: 'Assuming clumsy walking is normal.', guidance: 'Detail sensory toe-walking, dyspraxia, poor depth perception, and tripping.', buzzwords: 'Walks on tiptoes, poor balance, trips and falls multiple times daily.', exampleASD: '[Child] walks almost permanently on tiptoes. They have very poor spatial awareness and tripping over curbs and their own feet is common, falling 6 to 8 times every week.' },
    { step: 'mobility', qNum: 'Question 39', officialTitle: 'Is Walking Dangerous to the Child\'s Health?', component: 'Danger Test', pitfall: 'Failing to link uncoordinated walking with street injury.', guidance: 'Explain that sudden meltdowns and falls on pavements cause immediate injury.', buzzwords: 'Severe danger of injury, drops head-first onto concrete pavement.', exampleASD: 'Walking outdoors is dangerous because when overwhelmed, [Child] throws themselves backwards onto hard concrete without breaking their fall, causing repeated head bumps and cuts.' },
    { step: 'mobility', qNum: 'Question 40', officialTitle: 'Does Walking Cause Severe Mental or Physical Distress?', component: 'Distress Test', pitfall: 'Downplaying meltdowns as bad moods.', guidance: 'Explain that sensory overload outdoors triggers genuine physiological panic.', buzzwords: 'Sheer panic, uncontrollable screaming, severe sensory terror.', exampleASD: 'Being outside near busy roads causes immediate terror. Sirens, passing lorries, or barking dogs trigger instant screams, sweating, and violent attempts to break away and run.' },
    { step: 'mobility', qNum: 'Question 41', officialTitle: 'Does the Child Need Guidance or Supervision Outdoors?', component: 'Lower Rate Mobility (Supervision)', pitfall: 'Ticking that they can walk with verbal warnings.', guidance: 'Detail bolting, complete absence of road awareness, and need for a permanent wrist-hold.', buzzwords: 'Must be held firmly by hand/wrist at all times, no road awareness, runs into road.', exampleASD: '[Child] must be held by the hand or wrist with a firm grip 100% of the time. They have zero awareness of traffic danger and will bolt straight into moving traffic without looking if grip is broken for one second.' },
    { step: 'mobility', qNum: 'Question 42', officialTitle: 'Does the Child Get Lost or Disoriented Outdoors?', component: 'Orientation', pitfall: 'Assuming an older child naturally recognizes home routes.', guidance: 'Detail total lack of directional awareness and panic in familiar locations.', buzzwords: 'Completely disoriented, does not recognize home street, panics immediately.', exampleASD: 'Has no sense of direction whatsoever. Even on our own street right outside our front door, [Child] cannot tell which house is ours and panics instantly if they lose sight of me.' },
    { step: 'mobility', qNum: 'Question 43', officialTitle: 'Does the Child Behave Unpredictably Outdoors?', component: 'Behavioral Volatility', pitfall: 'Omitting flight and shutdown reactions.', guidance: 'Detail sudden dropping, bolting toward special interests, or public meltdowns.', buzzwords: 'Unpredictable, bolts towards headlights/water, drops to ground without warning.', exampleASD: 'Completely unpredictable. [Child] can suddenly sprint towards bright car headlights or puddles in the road, or instantly collapse dead-weight into muddy gutters.' },
    { step: 'mobility', qNum: 'Question 44', officialTitle: 'Can the Child Use Public Buses or Trains?', component: 'Transport Barriers', pitfall: 'Assuming public transit is manageable.', guidance: 'Detail how engine noise, vibrations, and strangers trigger acute meltdowns.', buzzwords: 'Cannot use public transport, screams and thrashes in enclosed noisy spaces.', exampleASD: 'Public transport is impossible. The engine noise, crowds, and feeling trapped trigger immediate screaming meltdowns where [Child] kicks the seats and attempts to climb out of moving buses.' },
    { step: 'mobility', qNum: 'Question 45', officialTitle: 'Does the Child Need Physical Help Getting On/Off Transport?', component: 'Transport Handling', pitfall: 'Leaving blank.', guidance: 'Detail physical handling required on transport steps during panic.', buzzwords: 'Must be physically lifted and carried on and off transport steps.', exampleASD: 'Must be physically lifted and carried up or down vehicle steps because they freeze in fear and cannot manage changes in floor levels.' },
    { step: 'mobility', qNum: 'Question 46', officialTitle: 'Problems Travelling in Cars or Taxis', component: 'Vehicle Safety', pitfall: 'Saying car travel is fine when meltdowns occur inside.', guidance: 'Detail unbuckling seatbelts, kicking windows, and sensory distress.', buzzwords: 'Unbuckles seatbelt while car is moving, kicks windows, screams.', exampleASD: 'Car travel is hazardous. [Child] constantly tries to unbuckle their seatbelt while driving, screams hysterically, and kicks windows, creating severe distractions.' },
    { step: 'mobility', qNum: 'Question 47', officialTitle: 'Does the Child Need Special Car Seats or Restraints?', component: 'Vehicle Safety Equipment', pitfall: 'Not mentioning anti-escape clips.', guidance: 'Detail specialized 5-point harnesses, chest clips, and window child locks.', buzzwords: 'Anti-escape buckle clips, 5-point harness, child locks permanently on.', exampleASD: 'Must use a high-backed seat with an anti-escape chest harness clip so they cannot undo the buckle while moving. Car doors and windows must stay permanently child-locked.' },
    { step: 'mobility', qNum: 'Question 48', officialTitle: 'Can the Child Cross Roads Safely?', component: 'Road Safety Deficit', pitfall: 'Saying Yes because they hold hands when forced.', guidance: 'Explain that left unattended, they have zero comprehension of moving vehicles.', buzzwords: 'No road safety sense, steps out in front of moving cars, unaware of danger.', exampleASD: 'Has zero concept of road safety. [Child] thinks the road is just a continuation of the pavement and will walk straight into oncoming traffic without stopping or looking left or right.' },
    { step: 'mobility', qNum: 'Question 49', officialTitle: 'Does the Child Freeze or Panic Near Traffic?', component: 'Sensory Traffic Panic', pitfall: 'Leaving blank.', guidance: 'Detail freezing on crossings when loud trucks pass.', buzzwords: 'Freezes on pedestrian crossings, screams at engine noise.', exampleASD: 'A revving engine, horn, or bus air-brake causes [Child] to drop to their knees in the middle of pedestrian crossings in complete panic, requiring me to physically drag or carry them across.' },
    { step: 'mobility', qNum: 'Question 50', officialTitle: 'Can the Child Cope with Changes to Outdoor Routes?', component: 'Cognitive Rigidity', pitfall: 'Downplaying detour meltdowns.', guidance: 'Explain that route changes break cognitive schemas, triggering multi-hour meltdowns.', buzzwords: 'Severe meltdown if route changes, cannot accept detours, screaming.', exampleASD: 'Taking a different road or making an unexpected turn causes immediate panic. [Child] screams, hits out, drops to the floor, and refuses to move until returned to the familiar route.' },
    { step: 'mobility', qNum: 'Question 51', officialTitle: 'Does the Child Need a Specialist Buggy or Stroller?', component: 'Mobility Equipment', pitfall: 'Assuming specialist buggies are just normal prams.', guidance: 'State that specialist buggies are medical safety aids for children beyond pram age.', buzzwords: 'Specialist disability stroller for safety, prevents running into traffic.', exampleASD: 'Must be strapped into a specialist large buggy for any journey longer than 50 metres to prevent them bolting into the road or collapsing on pavements.' },
    { step: 'mobility', qNum: 'Question 52', officialTitle: 'How Does Bad Weather Affect Mobility Outdoors?', component: 'Tactile Weather Impact', pitfall: 'Ignoring sensory weather sensitivity.', guidance: 'Explain how rain, cold, or wind intensifies tactile defensiveness, halting movement.', buzzwords: 'Rain touching face causes distress, wind triggers meltdowns and refusal.', exampleASD: 'Raindrops touching their face or hands cause extreme distress and screams of pain. Strong wind makes [Child] completely panic and refuse to move.' },
    { step: 'mobility', qNum: 'Question 53', officialTitle: 'Any Other Outdoor Mobility Difficulties?', component: 'Mobility Summary', pitfall: 'Leaving mobility summary blank.', guidance: 'Summarize the exhausting necessity of constant physical containment outdoors.', buzzwords: 'Needs continuous 1-to-1 physical grip and supervision outdoors at all times.', exampleASD: 'Every outdoor trip requires 100% constant physical hold and vigilance. Independent outdoor walking is impossible due to severe sensory panic, bolting, and lack of road awareness.' },

    // ==========================================
    // PART 3: DAYTIME CARE NEEDS (Q54 - Q62)
    // ==========================================
    { step: 'daycare', qNum: 'Question 54', officialTitle: 'Getting In and Out of Bed / Settling in Bed', component: 'Morning Transition', pitfall: 'Saying they wake up independently without noting transition battles.', guidance: 'Detail profound sleep inertia, executive paralysis, and 45+ minutes of physical coaxing.', buzzwords: 'Takes 45+ minutes to get out of bed, needs continuous gentle prompting and reassurance.', exampleASD: 'Cannot wake up and get out of bed on their own. Wakes up disoriented and distressed, requiring 40-45 minutes of gentle sitting with them, stroking their back, and repeated coaxing to sit up.' },
    { step: 'daycare', qNum: 'Question 55', officialTitle: 'Toileting Needs and Managing Continence', component: 'Personal Care (Toileting)', pitfall: 'Calling accidents laziness.', guidance: 'Explain impaired interoception (no urge awareness) and tactile aversion to wiping.', buzzwords: 'Does not feel urge to go, needs hourly toilet reminders, cannot wipe cleanly.', exampleASD: 'Does not recognise bodily signals that their bladder or bowel is full until they are leaking. Requires scheduled reminders every 60 minutes and full help wiping, as they cannot coordinate paper or tolerate the feel of it.' },
    { step: 'daycare', qNum: 'Question 56', officialTitle: 'Daytime Continence Accidents & Clean-Up', component: 'Incontinence Load', pitfall: 'Under-reporting weekly wetting or soiling frequency.', guidance: 'State the exact weekly accident frequency and parental cleanup burden.', buzzwords: 'Wet/soiled accidents 3-5 times weekly, requires full adult clean and clothing change.', exampleASD: 'Has 3 to 5 wetting and soiling accidents every week because they do not realise they need the toilet until it is too late. Requires complete adult washing and a full change of clothes each time.' },
    { step: 'daycare', qNum: 'Question 57', officialTitle: 'Washing, Bathing, Showering and Oral Hygiene', component: 'Personal Care (Hygiene)', pitfall: 'Writing they wash themselves because they splash water.', guidance: 'Detail sensory pain from water on face, scald hazards, and teeth brushing gag reflex.', buzzwords: 'Cannot wash alone, water on face causes screaming, gags on toothbrush, scald hazard.', exampleASD: 'Bath time requires two adults: one to comfort and hold, one to wash quickly. Water on their face causes screams of terror. Cannot test water temperature and will sit in scalding water. Teeth brushing causes choking and gagging.' },
    { step: 'daycare', qNum: 'Question 58', officialTitle: 'Dressing and Undressing During the Day', component: 'Personal Care (Dressing)', pitfall: 'Ticking they dress independently if they can pull on loose socks.', guidance: 'Detail tag removal, seam inversion, and inability to sequence clothing items.', buzzwords: 'Needs 100% help dressing, cannot sequence clothes, seams and tags cause meltdowns.', exampleASD: 'Cannot dress themselves. [Child] puts legs through head-holes and coats on backwards without constant help. All clothing tags must be cut out and seams checked, or contact with skin triggers a complete meltdown.' },
    { step: 'daycare', qNum: 'Question 59', officialTitle: 'Eating and Drinking', component: 'Personal Care (Feeding)', pitfall: 'Assuming feeding questions only apply if tube-fed.', guidance: 'Detail ARFID, restricted beige foods, food pocketing choking hazards, and coaxing.', buzzwords: 'Choking hazard, pockets food in cheeks, refuses food, needs constant encouragement.', exampleASD: 'Will only eat 3 or 4 specific foods of identical texture. Often pockets dry food in their cheeks for 30 minutes without swallowing, posing a serious choking hazard that requires someone sitting watching every bite.' },
    { step: 'daycare', qNum: 'Question 60', officialTitle: 'Taking Medication or Healthcare Treatments', component: 'Medical Oversight', pitfall: 'Leaving blank if they refuse pills.', guidance: 'Explain that extreme sensory taste defensiveness requires hiding medicine in purees.', buzzwords: 'Refuses medicine, spits out liquids, needs hiding in food, takes 30 mins.', exampleASD: 'Gags violently and spits out all liquid medicine due to sensory taste and texture issues. Medicine must be carefully hidden in specific fruit purees and coaxed spoonful by spoonful.' },
    { step: 'daycare', qNum: 'Question 61', officialTitle: 'Communicating Basic Daytime Needs', component: 'Communication Barrier', pitfall: 'Assuming talking a lot means functional communication.', guidance: 'Detail situational mutism, echolalia, and inability to report physical pain or thirst.', buzzwords: 'Cannot ask for food/drink, cannot express pain, loses speech when upset.', exampleASD: 'Cannot tell me when they are hungry, thirsty, or in physical pain. When overwhelmed or hurt, [Child] loses speech completely and cries or hits themselves, leaving me to guess what is wrong.' },
    { step: 'daycare', qNum: 'Question 62', officialTitle: 'Any Other Daytime Care Needs?', component: 'Daytime Summary', pitfall: 'Leaving daytime summary blank.', guidance: 'Summarize the constant, unrelenting nature of daytime supervision and co-regulation.', buzzwords: 'Care needs substantially in excess of a child of the same age throughout the day.', exampleASD: 'From morning to night, [Child] requires hands-on physical help with every basic bodily function—washing, dressing, eating, and toileting—far beyond what any ordinary child their age needs.' },

    // ==========================================
    // PART 4: SAFETY & DEVELOPMENT (Q63 - Q72)
    // ==========================================
    { step: 'safety', qNum: 'Question 63', officialTitle: 'Supervision Indoors to Avoid Substantial Danger', component: 'Substantial Danger Test', pitfall: 'Failing to explain what happens if your back is turned for 2 minutes.', guidance: 'Detail climbing worktops, turning on cookers, and domestic hazard deficits.', buzzwords: 'Continual supervision throughout the day to avoid substantial danger, climbs worktops, turns on cooker.', exampleASD: 'Cannot be left alone in a room for even 2 minutes. [Child] climbs onto kitchen worktops, turns on gas cooker knobs, and leans out of upstairs windows with zero fear or understanding of falling.' },
    { step: 'safety', qNum: 'Question 64', officialTitle: 'Dangerous Indoor Behaviors and Destruction', component: 'Domestic Safety', pitfall: 'Downplaying property damage as accidents.', guidance: 'Detail throwing heavy objects, breaking glass, and damaging fixtures during meltdowns.', buzzwords: 'Throws heavy objects during meltdowns, breaks glass, bangs doors violently.', exampleASD: 'During meltdowns, [Child] throws anything to hand—heavy wooden toys, cups, tablets—shattering items and damaging walls, putting themselves and anyone nearby in direct danger of injury.' },
    { step: 'safety', qNum: 'Question 65', officialTitle: 'Awareness of Common Household Hazards', component: 'Hazard Deficit', pitfall: 'Assuming an older child knows fire is dangerous.', guidance: 'Explain total absence of cause-and-effect thinking regarding heat, electricity, and knives.', buzzwords: 'No understanding of danger, touches hot hobs, picks up sharp knives.', exampleASD: 'Has no understanding that heat burns or knives cut. Will touch hot oven doors, attempt to grab knife blades from drying racks, and chew on electrical wires.' },
    { step: 'safety', qNum: 'Question 66', officialTitle: 'Communication and Social Vulnerability', component: 'Social Exploitation', pitfall: 'Saying they communicate fine because they talk endlessly about special interests.', guidance: 'Detail hyper-literal thinking, lack of stranger danger discernment, and social exploitation.', buzzwords: 'Zero stranger danger awareness, would walk off with anyone, easily exploited.', exampleASD: 'Has zero stranger danger awareness. [Child] treats every stranger as an immediate best friend and would happily hold hands and walk away with anyone in a supermarket or park.' },
    { step: 'safety', qNum: 'Question 67', officialTitle: 'Understanding Intentions of Others', component: 'Social Understanding', pitfall: 'Leaving blank.', guidance: 'Explain inability to read facial expressions, detect sarcasm, or realize they are being manipulated.', buzzwords: 'Cannot read body language, does not realise when being teased, highly naive.', exampleASD: 'Cannot read tone of voice or facial expressions. Takes jokes literally, does not realise when other children are being mean or daring them to do dangerous things, and gets upset very easily.' },
    { step: 'safety', qNum: 'Question 68', officialTitle: 'Behavioral Disturbance and Outbursts', component: 'Behavioral Oversight', pitfall: 'Calling meltdowns mere tantrums.', guidance: 'Detail explosive sensory overloads lasting 45-90 minutes where reasoning is impossible.', buzzwords: 'Severe meltdowns lasting 45-60 minutes, screaming, thrashing, cannot be reasoned with.', exampleASD: 'Experiences severe sensory meltdowns lasting 45 to 60 minutes. [Child] thrashes on the floor, screams uncontrollably, and cannot hear or respond to verbal calming until the storm passes.' },
    { step: 'safety', qNum: 'Question 69', officialTitle: 'Does the Child Harm Themselves?', component: 'Self-Harm & Injury', pitfall: 'Hiding head-banging or biting out of shame.', guidance: 'Detail self-injurious actions during sensory overloads (head-banging on tile floors, skin-biting).', buzzwords: 'Bangs head on floors/walls, bites hands until bruised, pulls hair.', exampleASD: 'When overwhelmed, [Child] bangs their forehead repeatedly against hard tiled floors and walls, and bites their own hands until skin is red, bruised, and marked.' },
    { step: 'safety', qNum: 'Question 70', officialTitle: 'Does the Child Require Physical Intervention?', component: 'Physical Restraint', pitfall: 'Leaving blank out of embarrassment.', guidance: 'Detail holding the child to prevent severe head trauma, road-running, or injury.', buzzwords: 'Must be physically held and restrained to prevent serious head injury.', exampleASD: 'I must physically step in to slide my hands or cushions between their head and hard floors, or hold them firmly in a cuddle to stop them injuring themselves or running toward roads.' },
    { step: 'safety', qNum: 'Question 71', officialTitle: 'PICA or Mouthing Inappropriate Objects', component: 'PICA Risk', pitfall: 'Assuming mouthing stops in infancy.', guidance: 'Detail chewing and swallowing batteries, plastics, cables, clothing, or foam.', buzzwords: 'Puts dangerous objects in mouth, chews plastic/cables, choking/poison hazard.', exampleASD: 'Constantly chews and mouths non-food items: cushions, buttons, coins, plastic toys, and charging cables. Requires vigilant monitoring to prevent swallowing dangerous objects or choking.' },
    { step: 'safety', qNum: 'Question 72', officialTitle: 'Any Other Safety or Developmental Needs?', component: 'Safety Summary', pitfall: 'Leaving safety summary blank.', guidance: 'Summarize the exhausting necessity of 100% continuous line-of-sight supervision indoors.', buzzwords: 'Requires constant line-of-sight supervision indoors to avoid substantial danger.', exampleASD: 'Due to severe lack of danger awareness, self-harm, and impulsive climbing, [Child] cannot be left out of sight for even a minute inside our home without serious risk of injury.' },

    // ==========================================
    // PART 5: NIGHT-TIME CARE & EXTRA INFORMATION (Q73 - Q84)
    // ==========================================
    { step: 'night', qNum: 'Question 73', officialTitle: 'Help Needed During the Night (11pm to 7am)', component: 'Higher Rate Care Trigger', pitfall: 'Thinking night waking is just ordinary bad sleep.', guidance: 'Must wake 2-3+ times OR require attention for at least 20 minutes to qualify for Higher Rate Care.', buzzwords: 'Wakes 2-3 times every night, takes 45 mins to settle each time, prolonged attention.', exampleASD: '[Child] wakes 2 to 3 times every night in a distressed, wide-awake state. Each waking requires 30 to 45 minutes of active parental settling, soothing, and checking for safety.' },
    { step: 'night', qNum: 'Question 74', officialTitle: 'How Many Times Does the Child Wake Up?', component: 'Night Waking Frequency', pitfall: 'Guessing instead of logging actual interruptions.', guidance: 'State the exact nightly frequency (e.g. 2 to 4 times every single night).', buzzwords: 'Consistently wakes 2 to 4 times every single night.', exampleASD: 'Wakes on average 2 to 4 times every night throughout the week, unable to get back to sleep without direct parental presence.' },
    { step: 'night', qNum: 'Question 75', officialTitle: 'How Long Does Each Waking Episode Last?', component: 'Night Duration', pitfall: 'Claiming they settle in 5 minutes.', guidance: 'Explain that calming an autistic nervous system at 3 AM takes 30 to 50 minutes.', buzzwords: 'Takes 30 to 50 minutes of active comforting and monitoring per waking.', exampleASD: 'Each waking episode takes between 35 and 50 minutes of sitting in their bedroom, rubbing their back, and keeping them calm before they fall back to sleep.' },
    { step: 'night', qNum: 'Question 76', officialTitle: 'What Attention Does the Child Need at Night?', component: 'Night Care Actions', pitfall: 'Saying you just hand them a drink.', guidance: 'Detail preventing nighttime wandering, deep touch massage, and guarding against falls.', buzzwords: 'Prevents dangerous night wandering, physical soothing, checking breathing/safety.', exampleASD: 'I have to physically get out of bed, stop [Child] from wandering the house in the dark or opening external doors, provide drinks, and stay by their side until they are calm.' },
    { step: 'night', qNum: 'Question 77', officialTitle: 'Does the Child Wet or Soil the Bed at Night?', component: 'Nocturnal Enuresis', pitfall: 'Calling nighttime bedwetting normal for an older child.', guidance: 'Detail nocturnal enuresis, lack of wake-up reflex, and pull-up usage.', buzzwords: 'Nightly bedwetting, deep sleep unaware of bladder, wears pull-ups.', exampleASD: 'Experiences nightly bedwetting because they do not wake up to bladder signals. Wears heavy-absorbency pull-ups every single night, which regularly leak through to sheets.' },
    { step: 'night', qNum: 'Question 78', officialTitle: 'How Often Do Nighttime Bedwetting Accidents Occur?', component: 'Accident Frequency', pitfall: 'Minimizing accidents as rare.', guidance: 'State exact weekly frequency (e.g. 6 to 7 nights per week).', buzzwords: 'Occurs 6 to 7 nights every week.', exampleASD: 'Bedwetting occurs 7 nights a week, with pull-up leaks and wet bed sheets happening 3 to 4 times every week.' },
    { step: 'night', qNum: 'Question 79', officialTitle: 'What Help is Needed with Nighttime Incontinence?', component: 'Accident Clean-Up', pitfall: 'Saying they change themselves.', guidance: 'Detail waking up, stripping wet sheets, washing the child, and changing pajamas in the dark.', buzzwords: 'Stripping wet bed sheets, washing child in middle of night, fresh clothes.', exampleASD: 'I have to wake up, strip cold wet bedding and waterproof sheets, wash [Child] with wipes to prevent skin soreness, and put fresh pyjamas on them in the middle of the night.' },
    { step: 'night', qNum: 'Question 80', officialTitle: 'Seizures, Fits or Medical Episodes at Night', component: 'Nocturnal Medical Episodes', pitfall: 'Confusing bad dreams with clinical seizures.', guidance: 'State none if no epilepsy, or detail nocturnal panic, sensory night terrors, and breath holding.', buzzwords: 'Severe night terrors, wakes screaming and thrashing in panic.', exampleASD: 'No epilepsy, but suffers severe night terrors where [Child] wakes up thrashing, screaming hysterically, and disoriented, requiring holding and containment to stop them falling out of bed.' },
    { step: 'night', qNum: 'Question 81', officialTitle: 'Does the Child Need Medication at Night?', component: 'Night Medication', pitfall: 'Leaving blank if given at bedtime.', guidance: 'Detail melatonin administration, second doses, or calming remedies given during night wakings.', buzzwords: 'Administering prescribed melatonin and settling liquids at night.', exampleASD: 'Administer prescribed melatonin at bedtime, and provide soothing water or prescribed skin creams during 2 AM wake-ups.' },
    { step: 'night', qNum: 'Question 82', officialTitle: 'Does Anyone Stay Awake to Watch Over the Child at Night?', component: 'Night Watcher Criteria', pitfall: 'Saying No because you sleep in your own bed (even though you are awake half the night).', guidance: 'Explain that broken sleep and constant monitoring amount to an active night watch.', buzzwords: 'Broken sleep pattern, active night watch, listening on baby monitor.', exampleASD: 'I am constantly on alert via a video baby monitor. Because [Child] wakes 2 to 3 times nightly and attempts to wander, my own sleep is severely interrupted every single night.' },
    { step: 'night', qNum: 'Question 83', officialTitle: 'Any Other Special Nighttime Needs?', component: 'Night Adaptations', pitfall: 'Leaving blank.', guidance: 'Detail bedroom door alarms, specialized high-security window latches, and monitor cameras.', buzzwords: 'Door chime alarms, window safety locks, video monitor.', exampleASD: 'We have had to fit safety window restrictors and chime sensors on their bedroom door so that an alarm sounds downstairs if they try to wander in the dark.' },
    { step: 'night', qNum: 'Question 84', officialTitle: 'Extra Information (24-Hour Master Summary Statement)', component: 'Final Impact Statement', pitfall: 'Leaving this blank or writing a single brief sentence.', guidance: 'Summarize the relentless, exhausting 24-hour caregiver burden and contrast against a neurotypical child.', buzzwords: 'Care and supervision substantially in excess of a child of the same age, 24 hours a day.', exampleASD: 'In summary, [Child] requires continuous care, physical assistance, and vigilance 24 hours a day that is substantially in excess of what any child of the same age requires. From morning dressing and mealtimes to outdoor safety and repeated nighttime wakings, they cannot manage without constant adult supervision to prevent substantial danger and meet their basic needs.' }
];